Solved this random error when copy and paste at end of file 0x1000 bytes: display.c:156 Error calling ncurses refresh. Error calling ncurses delwin. the long seek failed (-1 instead of 54792), leaving :(